polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('plot/<int:pk>/', views.get_svg, name='plot'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
		
class Age(models.Model):
    range_list = [
        '0~20', '21~30', '31~40', '41~50', '51~60', '61~'
        ]
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    age_range = models.CharField(max_length=50)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return str(self.votes)

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
import io
import matplotlib.pyplot as plt
import numpy as np

from .models import Choice, Question, Age

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
   question = get_object_or_404(Question, pk=question_id)
   return render(request, 'polls/detail.html', {
       'question': question,
	   })

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    choices = question.choice_set.all()
    return render(request, 'polls/results.html', {
        'question': question,
        'choices': choices,
        })

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_age_id = ((int(request.POST['choice']) - 1) * 6) + int(request.POST['age'])
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        selected_choice_age = selected_choice.age_set.get(pk=selected_age_id)
    except (KeyError, Choice.DoesNotExist, Age.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice_age.votes += 1
        selected_choice_age.save()
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    
# グラフ作成
def setPlt(pk):
	question = get_object_or_404(Question, pk=pk)
	choices = question.choice_set.all()
	
	N, K = len(Age.range_list), choices.count()
	data = []
	
	for choice in choices:
		for age in choice.age_set.all():
			data.append(age.votes)
	
	data = np.reshape(data, (N, K), order="F") #列ごとにchoiceの結果を格納する
	
	normalized = data / data.sum(axis=1, keepdims=True) #6行2列を維持したまま比率を取得
	cumulative = np.zeros(N)
	tick = np.arange(N)
	cmap = plt.get_cmap("tab10")

	for k in range(K):
		color = plt.cm.autumn(float(k) / K, 1)
		plt.barh(tick, normalized[:, k], left=cumulative, color=color, label=choices[k]) #k列のグラフをN行分leftに積み上げる
		cumulative += normalized[:, k]

	plt.xlim((0, 1))
	plt.xlabel("rate")
	plt.ylabel("age")
	plt.yticks(tick, Age.range_list)
	plt.legend()
	plt.plot()
 
 
# svgへの変換
def pltToSvg():
    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight')
    s = buf.getvalue()
    buf.close()
    return s
 
 
def get_svg(request, pk):
    setPlt(pk)       # create the plot
    svg = pltToSvg() # convert plot to SVG
    plt.cla()        # clean up plt so it can be re-used
    response = HttpResponse(svg, content_type='image/svg+xml')
    return response

polls/templates/polls/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}

<p>
<h3>your age</h3>
<input type="radio" name="age" value="1" />
<label> 0~20 </label>
<input type="radio" name="age" value="2" />
<label> 21~30 </label>
<input type="radio" name="age" value="3" />
<label> 31~40 </label>
<input type="radio" name="age" value="4" />
<label> 41~50 </label>
<input type="radio" name="age" value="5" />
<label> 51~60 </label>
<input type="radio" name="age" value="6" />
<label> 60~ </label>
</p>
<input type="submit" value="Vote" />
</form>

<a href= "{% url 'polls:index' %}">TOP</a>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>POLL</h1>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>

{% else %}
    <p>No polls are available.</p>
{% endif %}
    

polls/templates/polls/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}</li>
{% endfor %}

<details>
	<summary>Details</summary>
	{% for choice in question.choice_set.all %}
		</br><li>{{ choice.choice_text }}</li>
		<ul class="age_list">
		{% for age in choice.age_set.all %}
			<li type=circle><{{ age.age_range }} -- {{ age.votes }}votes> </li>
		{% endfor %}
		</ul>
	{% endfor %}
</details>
</ul>

{% block content %} 
<img src='{% url 'polls:plot' question.id %}' width=500 height=500, align="top">
{% endblock %}

<p><a href="{% url 'polls:detail' question.id %}">Vote again?</a></p>

<a href="{% url 'polls:index' %}">TOP</a>